[package]
name = "rnav"
version = "0.1.1"
edition = "2024"
license = "MIT"
readme = "README.md"
description = "Terminal log navigator"
repository = "https://github.com/yonatan-linik/rnav"
keywords = ["log", "tui", "viewer", "navigator"]
categories = ["command-line-utilities", "filesystem", "text-processing"]

[lints.clippy]
all = "warn"
pedantic = "warn"
nursery = "warn"

[lib]
name = "rnav"
test = true
doctest = true

[dependencies]
chrono = "0.4.43"
clap = { version = "4.5.58", features = ["derive"] }
color-eyre = "0.6.5"
crossterm = "0.29.0"
itertools = "0.14.0"
num-format = "0.4.4"
rand = "0.10.0"
ratatui = "0.30.0"
regex = "1.12.3"
strum = { version = "0.27.2", features = ["strum_macros"] }
thiserror = "2.0.18"
memmap2 = "0.9"
