[package]
name = "rnav"
version = "0.2.0"
edition = "2024"
license = "MIT"
readme = "README.md"
description = "Terminal log navigator"
repository = "https://github.com/yonatan-linik/rnav"
keywords = ["log", "tui", "viewer", "navigator"]
categories = ["command-line-utilities", "filesystem", "text-processing"]

[lib]
name = "rnav"
test = true
doctest = true

[dependencies]
chrono = "0"
clap = { version = "4", features = ["derive"] }
color-eyre = "0"
crossterm = "0"
itertools = "0"
num-format = "0"
rand = "0"
ratatui = "0"
regex = "1"
strum = { version = "0", features = ["strum_macros"] }
thiserror = "2"
memmap2 = "0"
zip = "8"
tempfile = "3"
flate2 = { version = "1"}
