version: 2.1

orbs:
  rust: circleci/rust@1.6.2

jobs:
  build:
    docker:
      - image: cimg/rust:1.93.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-v1-{{ checksum "Cargo.lock" }}
      - run:
          name: Install Rustup
          command: |
            if ! command -v rustup &> /dev/null; then
              curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
              source "$HOME/.cargo/env"
            fi
      - rust/build:
          crate: .
          release: true
      - save_cache:
          key: cargo-v1-{{ checksum "Cargo.lock" }}
          paths:
            - ~/.cargo
  test:
    docker:
      - image: cimg/rust:1.93.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-v1-{{ checksum "Cargo.lock" }}
      - run:
          name: Install Rustup
          command: |
            if ! command -v rustup &> /dev/null; then
              curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
              source "$HOME/.cargo/env"
            fi
      - rust/test:
          package: .

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
