version: 2.1

orbs:
  rust: circleci/rust@1.6.2

jobs:
  build:
    docker:
      - image: cimg/rust:1.49.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-v1-{{ checksum "Cargo.lock" }}
      - rust/install
      - rust/build:
          crate: .
          release: true
      - save_cache:
          key: cargo-v1-{{ checksum "Cargo.lock" }}
          paths:
            - ~/.cargo
  test:
    docker:
      - image: cimg/rust:1.49.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-v1-{{ checksum "Cargo.lock" }}
      - rust/install
      - rust/test:
          package: .

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
