version: 2.1

orbs:
  rust: circleci/rust@1.6.2

jobs:
  build:
    docker:
      - image: cimg/rust:1.49.0
    steps:
      - checkout
      - rust/install
      - rust/build:
          crate: .
          release: true
  test:
    docker:
      - image: cimg/rust:1.49.0
    steps:
      - checkout
      - rust/install
      - rust/test:
          package: .

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build